language: php

php:
    - 5.3
    - 5.5

env:
    - WP_VERSION=3.0.6
    - WP_VERSION=3.5.2
    - WP_VERSION=3.6.1

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - fgrep wp_version /tmp/wordpress/wp-includes/version.php

script: phpunit
