language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

env:
    - WP_VERSION=3.7
    - WP_VERSION=3.8
    - WP_VERSION=latest

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - fgrep wp_version /tmp/wordpress/wp-includes/version.php

script: phpunit
